[package]
name = "saya-connectors"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
saya-config = { path = "../saya-config" }
saya-types = { path = "../saya-types" }
futures-util.workspace = true
serde_json.workspace = true
sqlparser.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
chrono.workspace = true
uuid.workspace = true
bigdecimal.workspace = true
duckdb.workspace = true

[dev-dependencies]
tokio.workspace = true
