//! The M5-5 nested-saya battery: what a re-entering `saya` child can
//! actually see and open, proven through a real spawn — the escape battery
//! (tests/runner.rs) is the precedent for how a constraint is proven here.
//!
//! 1. **The re-entry test.** With the environment pinned, the child's world
//!    holds no production profile: the generated `connections.toml` it opens
//!    lacks it, the child's own user-layer resolution lands inside run state
//!    where nothing exists, and the planted real user config is denied by
//!    the sandbox outright. Asserted on what the child could actually open
//!    — its own report — never on a flag.
//! 2. **The generated-config sentinel scan, through a real spawn.** A
//!    planted resolved value reaches the child's environment exactly once
//!    (the declared endpoint var, reported hashed so no captured lane ever
//!    carries the value), appears in no generated byte under the run dir,
//!    and rides no other channel — not the argv it received, not another
//!    environment entry. A resolved secret on disk fails this test forever.
//! 3. **The cwd pin.** The child's cwd is the run workspace; a
//!    `connections.toml` planted in the *parent's* cwd is not discovered by
//!    the child's own discovery scan — and the sandbox denies reading it by
//!    path. Both closures, not either.
//! 4. **The environment pins.** The child's `SAYA_CONFIG_HOME`,
//!    `SAYA_STATE_DB`, and `SAYA_SESSION_DIR` all resolve inside
//!    `runs/<id>/state/`.
//!
//! Spawn-dependent, so like the escape battery this file needs the startup
//! probe to prove the sandbox: macOS today (the M5-3 decision this slice
//! consumes); elsewhere it compiles to an empty main. The pure composition
//! (argv shape, pin locations, credential mapping) is tested
//! unconditionally, above the battery.

use std::{fs, path::PathBuf};

use saya_harness::endpoints::{CorpusProfile, EndpointSpec};
use saya_harness::run_dir::RunDir;
use saya_harness::runner::nested_saya;
use saya_types::{EndpointBindings, RunId, SecretRef};

fn temp_root(label: &str) -> PathBuf {
    std::env::temp_dir().join(format!("saya-nested-{label}-{}", std::process::id()))
}

fn temp_run(label: &str, id: &str) -> RunDir {
    let root = temp_root(label);
    let _ = fs::remove_dir_all(&root);
    RunDir::create(&root, &RunId::parse(id).unwrap()).unwrap()
}

fn endpoint(name: &str, api_key: Option<SecretRef>) -> EndpointSpec {
    EndpointSpec {
        name: name.to_string(),
        provider: "anthropic".to_string(),
        model: "claude-test-model".to_string(),
        base_url: Some("https://api.test".to_string()),
        api_key,
    }
}

fn corpus(name: &str, path: &str) -> CorpusProfile {
    CorpusProfile {
        name: name.to_string(),
        path: path.to_string(),
    }
}

// -- the composition, on every platform CI covers ---------------------------

#[test]
fn the_composed_argv_is_the_bench_question_shape() {
    let run = temp_run("compose-argv", "argv-1");
    let state = nested_saya::prepare(
        &run,
        &[endpoint("orchestrator", None)],
        &Default::default(),
        &[],
    )
    .unwrap();
    assert_eq!(
        state.ask_argv("orchestrator", "how many orders?"),
        vec![
            "ask".to_owned(),
            "--config".into(),
            run.state()
                .join("config")
                .join("config.toml")
                .display()
                .to_string(),
            "--connections".into(),
            run.state()
                .join("config")
                .join("connections.toml")
                .display()
                .to_string(),
            "--profile".into(),
            "orchestrator".into(),
            "--non-interactive".into(),
            "--trust-project-config".into(),
            "--approval-mode".into(),
            "read-only".into(),
            "--format".into(),
            "ndjson".into(),
            "how many orders?".into(),
        ],
        "the invocation shape is bench.py:321-332, flag order pinned, plus the trust flag"
    );
    let _ = fs::remove_dir_all(run.root());
}

#[test]
fn prepare_generates_the_child_configs_and_pins_everything_inside_state() {
    let run = temp_run("compose-pins", "pins-1");
    let state = nested_saya::prepare(
        &run,
        &[endpoint("orchestrator", None)],
        &Default::default(),
        &[],
    )
    .unwrap();
    assert!(state.config_toml().exists(), "the generated config exists");
    assert!(
        state.connections_toml().exists(),
        "the generated connections exist"
    );
    assert_eq!(
        state.state_dir(),
        run.state(),
        "the pinned world is the run state"
    );
    for (name, path) in state.pinned_env() {
        assert!(
            path.starts_with(run.state()),
            "{name}={path:?} must resolve inside runs/<id>/state"
        );
    }
    let _ = fs::remove_dir_all(run.root());
}

#[test]
fn endpoint_credentials_mirror_the_generated_bindings() {
    let reference = SecretRef::Env {
        env: "SAYA_TEST_KEY_SOURCE".to_string(),
    };
    let endpoints = vec![
        endpoint("primary", Some(reference)),
        endpoint("orchestrator", None),
    ];
    let bindings = EndpointBindings::new([("orchestrator", "primary")]).unwrap();

    let credentials = nested_saya::endpoint_credentials(&endpoints, &bindings).unwrap();
    assert_eq!(credentials.len(), 1, "only the bound endpoint has a key");
    assert_eq!(credentials[0].env_var(), "SAYA_RUN_EP_ORCHESTRATOR");
    assert_eq!(credentials[0].name(), "primary");

    // Two roles uppercasing to one env name are refused, mirroring
    // `write_run_configs`' own duplicate-binding refusal.
    let colliding =
        EndpointBindings::new([("review-1", "primary"), ("review_1", "primary")]).unwrap();
    assert!(nested_saya::endpoint_credentials(&endpoints, &colliding).is_err());
}

#[cfg(not(target_os = "macos"))]
fn main() {}

#[cfg(target_os = "macos")]
mod spawn_battery {
    use std::{
        fs,
        path::{Path, PathBuf},
        process::Command,
        sync::OnceLock,
        time::Duration,
    };

    use saya_agent::CancellationToken;
    use saya_harness::run_dir::RunDir;
    use saya_harness::runner::StaticCredentialSource;
    use saya_harness::runner::nested_saya::{self, NESTED_PROGRAM, NestedAsk};
    use saya_harness::runner::sandbox::{RunSandbox, RunnerSpawn};
    use saya_types::{EndpointBindings, RunId, RunnerScope, SecretRef};

    use super::{corpus, endpoint};

    /// The nested child's timeout in the battery.
    const DEFAULT_TIMEOUT: Duration = Duration::from_secs(300);
    /// The profile the child answers as: the run's orchestrator role.
    const PROFILE: &str = "orchestrator";
    /// The planted resolved value: distinctive enough to byte-scan for, and
    /// free of the redactor's markers so the scan sees the truth.
    const PLANTED_VALUE: &str = "planted-9f3a-o4fJq9xZ-resolved-value";
    const PLANTED_VAR: &str = "SAYA_NESTED_SECRET_SOURCE";
    /// The production profile name planted in the world the child must not
    /// reach.
    const PRODUCTION_PROFILE: &str = "analytics_prod";

    fn leak(tag: &str) -> PathBuf {
        let path =
            std::env::temp_dir().join(format!("saya-nested-test-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("battery root must be creatable");
        fs::canonicalize(&path).expect("battery root must canonicalise")
    }

    fn scope() -> RunnerScope {
        RunnerScope::new(vec![NESTED_PROGRAM.to_owned()]).expect("shaped")
    }

    // -- the compiled stand-in for the `saya` binary ------------------------

    /// The battery's one helper program, compiled with the same toolchain
    /// running the tests and staged as `saya` in the program directory: it
    /// accepts the nested argv shape and reports what it could actually
    /// open — its cwd, its environment (pinned paths raw, every other value
    /// hashed so no captured lane carries a secret), each file it was
    /// pointed at, the user layer its own resolution implies, its cwd's
    /// `.saya/` discovery, and one probe path (the question slot doubles as
    /// a probe path). A file it manages to open is echoed byte for byte, so
    /// a leak reaches the capture and the test sees it.
    const HELPER_SOURCE: &str = r#"
use std::{env, fs};
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}
fn open_report(label: &str, path: &str) {
    match fs::read_to_string(path) {
        Ok(text) => {
            println!("open:{label}:{path}:ok");
            print!("{text}");
            if !text.is_empty() && !text.ends_with('\n') {
                println!();
            }
        }
        Err(error) => println!("open:{label}:{path}:denied({error})"),
    }
}
fn main() {
    let args: Vec<String> = env::args().collect();
    if args.get(1).map(String::as_str) != Some("ask") {
        eprintln!("the nested argv shape is `ask ...`; got {:?}", args.get(1));
        std::process::exit(2);
    }
    let (mut config, mut connections, mut question) =
        (String::new(), String::new(), String::new());
    let mut index = 2;
    while index < args.len() {
        match args[index].as_str() {
            "--config" => {
                config = args.get(index + 1).cloned().unwrap_or_default();
                index += 2;
            }
            "--connections" => {
                connections = args.get(index + 1).cloned().unwrap_or_default();
                index += 2;
            }
            "--profile" | "--approval-mode" | "--format" => index += 2,
            "--non-interactive" | "--trust-project-config" => index += 1,
            other => {
                question = other.to_owned();
                index += 1;
            }
        }
    }
    for (index, arg) in args.iter().enumerate() {
        let hex: String = arg.bytes().map(|b| format!("{b:02x}")).collect();
        println!("arg{index}={hex}");
    }
    println!("cwd={}", env::current_dir().unwrap().display());
    for name in ["SAYA_CONFIG_HOME", "SAYA_STATE_DB", "SAYA_SESSION_DIR"] {
        println!("env-pin:{name}={}", env::var(name).unwrap_or_else(|_| "<unset>".into()));
    }
    let mut vars: Vec<(String, String)> = env::vars().collect();
    vars.sort();
    for (name, value) in vars {
        if matches!(
            name.as_str(),
            "SAYA_CONFIG_HOME" | "SAYA_STATE_DB" | "SAYA_SESSION_DIR"
        ) {
            continue;
        }
        println!("env-hashed:{name}:{}:{:016x}", value.len(), fnv1a(value.as_bytes()));
    }
    open_report("config", &config);
    open_report("connections", &connections);
    if let Ok(home) = env::var("SAYA_CONFIG_HOME") {
        open_report("user-config", &format!("{home}/saya/config.toml"));
        open_report("user-connections", &format!("{home}/saya/connections.toml"));
    }
    let discovered = env::current_dir().unwrap().join(".saya/connections.toml");
    println!(
        "discover:{}:{}",
        discovered.display(),
        if discovered.exists() { "found" } else { "missing" }
    );
    if !question.is_empty() {
        open_report("probe", &question);
    }
}
"#;

    fn helper() -> &'static PathBuf {
        static HELPER: OnceLock<PathBuf> = OnceLock::new();
        HELPER.get_or_init(|| {
            let base = std::env::var("CARGO_TARGET_TMPDIR")
                .map(PathBuf::from)
                .unwrap_or_else(|_| std::env::temp_dir());
            let dir = base.join(format!("saya-nested-helper-{}", std::process::id()));
            let _ = fs::remove_dir_all(&dir);
            fs::create_dir_all(&dir).expect("helper directory must be creatable");
            let source = dir.join("saya-nested-helper.rs");
            let binary = dir.join("saya-nested-helper");
            fs::write(&source, HELPER_SOURCE).expect("helper source must be written");
            let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_owned());
            let status = Command::new(rustc)
                .arg("--edition=2021")
                .arg("-o")
                .arg(&binary)
                .arg(&source)
                .status()
                .expect("rustc must be runnable — it is the toolchain running this test");
            assert!(status.success(), "the nested helper must compile: {status}");
            binary
        })
    }

    // -- the battery: one proven provision per test, its own run dir --------

    struct Battery {
        run: RunDir,
        spawn: RunnerSpawn,
    }

    /// Builds one battery: a run dir with its `workspace/` and `state/`, the
    /// staged helper — outside the roots, a child must not rewrite its own
    /// allowlist — and the startup probe's verdict over the policy whose
    /// first root is the run workspace (the cwd pin's requirement).
    fn battery(tag: &str, id: &str) -> Battery {
        let runs_root = leak(tag);
        let run = RunDir::create(&runs_root, &RunId::parse(id).expect("shaped run id"))
            .expect("the run dir must create");
        let workspace = run.workspace().to_path_buf();
        let state = run.state().to_path_buf();
        let programs = leak(&format!("{tag}-programs"));
        fs::copy(helper(), programs.join(NESTED_PROGRAM)).expect("the helper must stage");
        let policy = RunSandbox::new([workspace, state], Vec::<(String, u16)>::new())
            .expect("the run workspace and state construct a policy");
        let provision = policy.prepare(&programs).expect("preparation must run");
        assert!(
            provision.report().proves_runner(),
            "the healthy-host probe must prove the nested battery:\n{}",
            provision.report().render()
        );
        Battery {
            run,
            spawn: provision
                .spawn()
                .expect("the provision must be proven")
                .clone(),
        }
    }

    // -- assertions on what the child reported ------------------------------

    /// The first line carrying `prefix`, if the child reported one.
    fn report_line<'a>(report: &'a str, prefix: &str) -> &'a str {
        report
            .lines()
            .find(|line| line.starts_with(prefix))
            .unwrap_or_else(|| panic!("the child must report {prefix:?}: {report}"))
    }

    /// Decodes the helper's `arg<i>=<hex>` echo back into the argv the child
    /// actually received (element 0 is the program path).
    fn received_argv(report: &str) -> Vec<String> {
        let mut received = Vec::new();
        for line in report.lines() {
            let Some((index, hex)) = line
                .strip_prefix("arg")
                .and_then(|rest| rest.split_once('='))
            else {
                continue;
            };
            assert_eq!(
                index.parse::<usize>().expect("arg index"),
                received.len(),
                "argv elements arrive in order"
            );
            let bytes = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex byte"))
                .collect::<Vec<u8>>();
            received.push(String::from_utf8(bytes).expect("the composed argv is UTF-8"));
        }
        assert_eq!(
            received.len(),
            15,
            "the child received the composed argv: {report}"
        );
        received
    }

    /// FNV-1a, byte-identical to the helper's.
    fn fnv1a(bytes: &[u8]) -> u64 {
        let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
        for byte in bytes {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
        hash
    }

    /// Every regular file under `root`, at any depth.
    fn run_files(root: &Path) -> Vec<PathBuf> {
        let mut files = Vec::new();
        let mut pending = vec![root.to_path_buf()];
        while let Some(dir) = pending.pop() {
            for entry in fs::read_dir(&dir).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    pending.push(path);
                } else {
                    files.push(path);
                }
            }
        }
        files
    }

    // -- test 1: the re-entry — no production profile in the child's world --

    /// The parent's environment carries a real user config home with a
    /// production profile in it; the nested child — its environment built,
    /// not inherited — must resolve its user layer inside run state where
    /// nothing exists, open the generated connections and find only the run
    /// corpus, and be denied the planted real config by path. Asserted on
    /// the child's own report of what it could open.
    #[tokio::test]
    async fn a_nested_saya_sees_no_production_profile_in_its_world() {
        // The real user config the child would resolve if its environment
        // were inherited, planted where the parent's SAYA_CONFIG_HOME points.
        let planted_home = leak("reentry-user-config");
        let user_saya = planted_home.join("saya");
        fs::create_dir_all(&user_saya).expect("the planted user config home");
        fs::write(
            user_saya.join("config.toml"),
            "[ai]\nmodel = \"prod-model\"\n",
        )
        .expect("the planted user config");
        fs::write(
            user_saya.join("connections.toml"),
            format!("[profiles.\"{PRODUCTION_PROFILE}\"]\npath = \"/data/warehouse.db\"\n"),
        )
        .expect("the planted production connections");
        // The parent's own env carries it — the child must not inherit it.
        unsafe { std::env::set_var("SAYA_CONFIG_HOME", &planted_home) };

        let battery = battery("reentry", "reentry-1");
        let state = nested_saya::prepare(
            &battery.run,
            &[endpoint("orchestrator", None)],
            &Default::default(),
            &[corpus("corp", "workspace/corpus/corp.db")],
        )
        .expect("the generated configs");
        let resolver = StaticCredentialSource::new(Vec::<(String, String)>::new());
        let cancellation = CancellationToken::new();
        // The question doubles as the probe path: the planted real user
        // connections, which the child must fail to open.
        let probe = user_saya.join("connections.toml");
        let outcome = nested_saya::ask(
            &battery.spawn,
            &scope(),
            &state,
            NestedAsk {
                profile: PROFILE,
                question: &probe.display().to_string(),
                credentials: &[],
                resolver: &resolver,
            },
            DEFAULT_TIMEOUT,
            &cancellation,
        )
        .await
        .expect("the nested ask must run");
        assert_eq!(outcome.exit_code, Some(0), "the child must have run");

        let report = &outcome.stdout.text;
        let state_dir = state.state_dir();
        // The child's own user-layer resolution points inside run state —
        // the planted parent env did not reach it — and finds nothing there.
        assert_eq!(
            report_line(report, "env-pin:SAYA_CONFIG_HOME="),
            format!(
                "env-pin:SAYA_CONFIG_HOME={}",
                state_dir.join("config-home").display()
            ),
            "the child's config home is the run state's, not the parent's"
        );
        let user_config = report_line(report, "open:user-config:");
        let resolved = state_dir.join("config-home/saya/config.toml");
        assert!(
            user_config.contains(":denied(")
                && user_config.contains(&resolved.display().to_string()),
            "the child's user config resolves inside run state and finds nothing: {user_config}"
        );
        assert!(
            report_line(report, "open:user-connections:").contains(":denied("),
            "the child's user connections find nothing: {report}"
        );
        // The generated connections it actually opened hold only the corpus.
        assert!(
            report.contains(&format!(
                "open:connections:{}:ok",
                state.connections_toml().display()
            )),
            "the child opened the generated connections: {report}"
        );
        assert!(
            report.contains("[profiles.\"corp\"]"),
            "the child opened and read the run's corpus: {report}"
        );
        assert!(
            !report.contains(PRODUCTION_PROFILE),
            "no production profile anywhere in the child's world: {report}"
        );
        // The sandbox denies the planted real config by path outright — the
        // outside closure beside the inside one.
        let probe_line = report_line(report, "open:probe:");
        assert!(
            probe_line.contains(":denied("),
            "the real user config is unreachable by path: {probe_line}"
        );

        unsafe { std::env::remove_var("SAYA_CONFIG_HOME") };
        let _ = fs::remove_dir_all(battery.run.root());
        let _ = fs::remove_dir_all(&planted_home);
    }

    // -- test 2: the sentinel scan, through a real spawn ---------------------

    /// The M5-2 byte-scan, re-run through a real spawn: the resolved value
    /// rides the spawn environment exactly once — the declared endpoint var
    /// — and lands in no generated byte under the run dir, no argv element,
    /// and no other environment entry.
    #[tokio::test]
    async fn the_generated_config_sentinel_scan_survives_a_real_spawn() {
        unsafe { std::env::set_var(PLANTED_VAR, PLANTED_VALUE) };
        let resolver =
            StaticCredentialSource::new([(PLANTED_VAR.to_owned(), PLANTED_VALUE.to_owned())]);

        let battery = battery("sentinel", "sentinel-1");
        let endpoints = vec![endpoint(
            "primary",
            Some(SecretRef::Env {
                env: PLANTED_VAR.to_string(),
            }),
        )];
        let bindings = EndpointBindings::new([("orchestrator", "primary")]).unwrap();
        let state = nested_saya::prepare(
            &battery.run,
            &endpoints,
            &bindings,
            &[corpus("corp", "workspace/corpus/corp.db")],
        )
        .expect("the generated configs");
        let credentials = nested_saya::endpoint_credentials(&endpoints, &bindings)
            .expect("the declared endpoint credentials");
        let cancellation = CancellationToken::new();
        let outcome = nested_saya::ask(
            &battery.spawn,
            &scope(),
            &state,
            NestedAsk {
                profile: PROFILE,
                question: "count orders per region",
                credentials: &credentials,
                resolver: &resolver,
            },
            DEFAULT_TIMEOUT,
            &cancellation,
        )
        .await
        .expect("the nested ask must run");
        assert_eq!(outcome.exit_code, Some(0), "the child must have run");

        let report = &outcome.stdout.text;
        // The child received the composed argv verbatim, and the planted
        // value is in none of it.
        let argv = received_argv(report);
        assert_eq!(
            &argv[1..],
            &state.ask_argv(PROFILE, "count orders per region")[..],
            "the child received the composed invocation, byte for byte"
        );
        assert!(
            argv.iter().all(|element| !element.contains(PLANTED_VALUE)),
            "a resolved value must never ride the argv"
        );
        // The child's environment is the three pins plus the one declared
        // credential — and its value is reported hashed, so the value never
        // enters a captured lane at all.
        let hashed: Vec<&str> = report
            .lines()
            .filter(|line| line.starts_with("env-hashed:"))
            .collect();
        let expected = format!(
            "env-hashed:SAYA_RUN_EP_ORCHESTRATOR:{}:{:016x}",
            PLANTED_VALUE.len(),
            fnv1a(PLANTED_VALUE.as_bytes())
        );
        assert_eq!(
            hashed,
            vec![expected.as_str()],
            "the child's env is the three pins plus the declared credential, carrying the \
             resolved value verbatim: {report}"
        );
        assert!(
            !report.contains(PLANTED_VALUE),
            "the resolved value must never ride the captured output"
        );
        assert!(
            !outcome.stderr.text.contains(PLANTED_VALUE),
            "the value must not ride stderr either"
        );
        // Every generated byte under the run dir: no resolved value — and
        // the original reference is replaced by the run-scoped one, not
        // echoed.
        let files = run_files(battery.run.root());
        assert!(
            files.len() >= 2,
            "the two config files must exist: {files:?}"
        );
        for file in &files {
            let bytes = fs::read(file).unwrap();
            assert!(
                !bytes
                    .windows(PLANTED_VALUE.len())
                    .any(|window| window == PLANTED_VALUE.as_bytes()),
                "a resolved secret value reached disk: {}",
                file.display()
            );
        }
        let config = fs::read_to_string(state.config_toml()).unwrap();
        assert!(config.contains("api_key = { env = \"SAYA_RUN_EP_ORCHESTRATOR\" }"));
        assert!(!config.contains(PLANTED_VAR));
        // The child opened that generated file — the scan above covers what
        // it read, echoed byte for byte.
        assert!(
            report.contains(&format!("open:config:{}:ok", state.config_toml().display())),
            "the child opened the generated config: {report}"
        );

        unsafe { std::env::remove_var(PLANTED_VAR) };
        let _ = fs::remove_dir_all(battery.run.root());
    }

    // -- test 3: the cwd pin, and the parent's bait ---------------------------

    /// The parent's cwd carries `.saya/connections.toml` — the file
    /// `saya-cli/src/config/sources.rs:17-25` auto-discovers from the
    /// current directory. The child's cwd is the run workspace, so its own
    /// discovery finds nothing; and the sandbox denies the bait by path
    /// outright. Both closures, not either. The parent's cwd is made real
    /// by moving the test process into the planted directory for the
    /// spawn — a regressed pin would land the child there, and the bait
    /// would be discovered.
    #[tokio::test]
    async fn the_child_cwd_is_the_workspace_and_the_parents_connections_are_not_discovered() {
        // The parent's cwd, with the auto-discovery bait planted in it.
        let parent = leak("parent-cwd");
        let bait_dir = parent.join(".saya");
        fs::create_dir_all(&bait_dir).expect("the planted .saya dir");
        let bait = bait_dir.join("connections.toml");
        fs::write(
            &bait,
            format!("[profiles.\"{PRODUCTION_PROFILE}\"]\npath = \"../../prod.db\"\n"),
        )
        .expect("the bait must plant");
        assert!(
            bait.is_file(),
            "the bait must exist for the negative to be meaningful"
        );

        let battery = battery("cwd", "cwd-1");
        let state = nested_saya::prepare(
            &battery.run,
            &[endpoint("orchestrator", None)],
            &Default::default(),
            &[corpus("corp", "workspace/corpus/corp.db")],
        )
        .expect("the generated configs");
        // The parent's cwd is real at spawn time: without the pin the child
        // would land here and discover the bait.
        struct CwdGuard(PathBuf);
        impl Drop for CwdGuard {
            fn drop(&mut self) {
                std::env::set_current_dir(&self.0).expect("restore cwd");
            }
        }
        let guard = CwdGuard(std::env::current_dir().expect("the test process has a cwd"));
        std::env::set_current_dir(&parent).expect("chdir into the planted parent cwd");

        let resolver = StaticCredentialSource::new(Vec::<(String, String)>::new());
        let cancellation = CancellationToken::new();
        let outcome = nested_saya::ask(
            &battery.spawn,
            &scope(),
            &state,
            NestedAsk {
                profile: PROFILE,
                // The question doubles as the probe path: the bait itself.
                question: &bait.display().to_string(),
                credentials: &[],
                resolver: &resolver,
            },
            DEFAULT_TIMEOUT,
            &cancellation,
        )
        .await
        .expect("the nested ask must run");
        drop(guard);
        assert_eq!(outcome.exit_code, Some(0), "the child must have run");

        let report = &outcome.stdout.text;
        let workspace = battery.run.workspace().display().to_string();
        assert!(
            report.contains(&format!("cwd={workspace}")),
            "the child's cwd is the run workspace, not the parent's: {report}"
        );
        assert!(
            report.contains(&format!(
                "discover:{}:missing",
                battery
                    .run
                    .workspace()
                    .join(".saya/connections.toml")
                    .display()
            )),
            "the child's own discovery scan of its cwd finds nothing: {report}"
        );
        assert!(
            report.contains(&format!("open:probe:{}:denied(", bait.display())),
            "the sandbox denies the bait by path outright: {report}"
        );
        assert!(
            !report.contains(PRODUCTION_PROFILE),
            "the bait's production profile is not in the child's world: {report}"
        );

        let _ = fs::remove_dir_all(battery.run.root());
        let _ = fs::remove_dir_all(&parent);
    }

    // -- test 4: the environment pins resolve inside runs/<id>/state/ --------

    #[tokio::test]
    async fn the_pinned_environment_resolves_inside_the_run_state() {
        let battery = battery("pins", "pins-1");
        let state = nested_saya::prepare(
            &battery.run,
            &[endpoint("orchestrator", None)],
            &Default::default(),
            &[corpus("corp", "workspace/corpus/corp.db")],
        )
        .expect("the generated configs");
        let resolver = StaticCredentialSource::new(Vec::<(String, String)>::new());
        let cancellation = CancellationToken::new();
        let outcome = nested_saya::ask(
            &battery.spawn,
            &scope(),
            &state,
            NestedAsk {
                profile: PROFILE,
                question: "count orders per region",
                credentials: &[],
                resolver: &resolver,
            },
            DEFAULT_TIMEOUT,
            &cancellation,
        )
        .await
        .expect("the nested ask must run");
        assert_eq!(outcome.exit_code, Some(0), "the child must have run");

        let report = &outcome.stdout.text;
        let state_dir = battery.run.state();
        for var in ["SAYA_CONFIG_HOME", "SAYA_STATE_DB", "SAYA_SESSION_DIR"] {
            let line = report_line(report, &format!("env-pin:{var}="));
            let value = PathBuf::from(
                line.strip_prefix(&format!("env-pin:{var}="))
                    .expect("the pin's value"),
            );
            assert!(
                value.starts_with(state_dir),
                "{var}={value:?} must resolve inside runs/<id>/state ({})",
                state_dir.display()
            );
        }
        // The child's own user-config resolution — the path its
        // SAYA_CONFIG_HOME implies — is inside run state too, and finds
        // nothing there: absence, not denial (DESIGN §6.4).
        let user_config = report_line(report, "open:user-config:");
        let resolved = state_dir.join("config-home/saya/config.toml");
        assert!(
            user_config.contains(":denied(")
                && user_config.contains(&resolved.display().to_string()),
            "the child's user layer resolves inside run state: {user_config}"
        );

        let _ = fs::remove_dir_all(battery.run.root());
    }
}
