[package]
name = "saya-store"
publish = false        # internal library; not published to crates.io
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
saya-types = { path = "../saya-types" }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
