#!/usr/bin/env python3
"""Writes the saya connection profiles the benchmark needs.

Everything lands in `.bench/spider/home/saya/`, which the runner selects with
`SAYA_CONFIG_HOME`. The user's own configuration is never read or written — a
benchmark that quietly edited someone's real profiles would be a nasty
surprise, and results would depend on whatever else they had configured.

Three families of profile:

  v1        one SQLite profile per Spider 1.0 database
  v2local   one SQLite profile per Spider 2.0 local database
  v2bq      one BigQuery profile per (database, dataset) pair

The BigQuery case is the awkward one. Twenty-nine of Spider 2.0's seventy
BigQuery "databases" actually span several BigQuery datasets — up to ten. saya
attaches one dataset per profile, so the extras are attached to the same
session with `--include-profile`; the runner reads which extras belong to which
database from the plan this script emits.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(ROOT, "..", ".."))
CORPUS = os.path.join(REPO, ".bench", "spider")
HOME = os.path.join(CORPUS, "home", "saya")

# A per-job scan ceiling. Spider 2.0's BigQuery questions sit on public tables
# that reach into the terabytes, and an unbounded cross join is one typo away;
# the connector refuses a query whose dry-run estimate exceeds this.
MAX_BYTES_BILLED = 10 * 1024**3


def sqlite_profiles(kind, root, suffix=".sqlite"):
    """Every SQLite database found under `root`, as `name -> file`."""
    out = {}
    if not os.path.isdir(root):
        return out
    if kind == "v1":
        # Spider 1.0 nests each database as database/<db>/<db>.sqlite
        for db in sorted(os.listdir(root)):
            path = os.path.join(root, db, f"{db}{suffix}")
            if os.path.exists(path):
                out[db] = path
    else:
        for f in sorted(os.listdir(root)):
            if f.endswith(suffix):
                out[f[: -len(suffix)]] = os.path.join(root, f)
    return out


def bigquery_profiles(project, location):
    """Profiles and the attach plan for the BigQuery suite."""
    path = f"{CORPUS}/bigquery_datasets.json"
    if not os.path.exists(path):
        return [], {}
    mapping = json.load(open(path))
    lines, plan = [], {}
    for db, datasets in sorted(mapping.items()):
        names = []
        for n, dataset in enumerate(datasets):
            name = f"bq_{db}" if n == 0 else f"bq_{db}__{n}"
            names.append(name)
            lines.append(f"""
[profiles.{name}]
type = "bigquery"
project = "{project}"
dataset = "{dataset}"
location = "{location}"
max_bytes_billed = {MAX_BYTES_BILLED}
service_account_key = {{ env = "SAYA_BQ_KEY" }}""")
        plan[db] = {"primary": names[0], "extras": names[1:],
                    "datasets": datasets}
    return lines, plan


def main():
    project = os.environ.get("SAYA_BQ_PROJECT")
    location = os.environ.get("SAYA_BQ_LOCATION", "US")
    os.makedirs(HOME, exist_ok=True)

    lines = ["# Generated by bench/spider/profiles.py — do not edit by hand.",
             "# Regenerate after changing the corpus."]

    v1 = sqlite_profiles("v1", f"{CORPUS}/spider_data/database")
    v2 = sqlite_profiles("v2local", f"{CORPUS}/s2local")
    for name, path in list(v1.items()) + list(v2.items()):
        lines.append(f"""
[profiles.{name}]
type = "sqlite"
path = "{path}"
read_only = true""")

    bq_lines, plan = ([], {})
    if project:
        bq_lines, plan = bigquery_profiles(project, location)
        lines += bq_lines
    json.dump(plan, open(f"{CORPUS}/bigquery_plan.json", "w"), indent=1)

    open(f"{HOME}/connections.toml", "w").write("\n".join(lines) + "\n")

    # The model config lives beside it so a run is fully described by
    # SAYA_CONFIG_HOME and nothing leaks in from the user's setup.
    if not os.path.exists(f"{HOME}/config.toml"):
        provider = os.environ.get("SAYA_BENCH_PROVIDER", "openai_compatible")
        model = os.environ.get("SAYA_BENCH_MODEL", "glm-5.2")
        base = os.environ.get("SAYA_BENCH_BASE_URL", "")
        cfg = [f'[ai]\nprovider = "{provider}"\nmodel = "{model}"']
        if base:
            cfg.append(f'base_url = "{base}"')
        # Spider is a public corpus, so rows may go to the model.
        cfg.append("allow_data_sharing = true")
        open(f"{HOME}/config.toml", "w").write("\n".join(cfg) + "\n")

    print(f"wrote {HOME}/connections.toml")
    print(f"  Spider 1.0 SQLite profiles : {len(v1)}")
    print(f"  Spider 2.0 local profiles  : {len(v2)}")
    if project:
        spanning = sum(1 for v in plan.values() if v["extras"])
        print(f"  BigQuery profiles          : {len(bq_lines)} "
              f"across {len(plan)} databases ({spanning} multi-dataset)")
    else:
        print("  BigQuery profiles          : skipped "
              "(set SAYA_BQ_PROJECT to include them)")
    if not v1 and not v2 and not project:
        print("\nnothing to do — run setup.py first")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
